##If the subscriptions in managed by Satellite, is TRUE
satellite_subs: true
path_inventory: "/root/inventory"


##FOR NON-SATELLITE
username_subscription: "username"
password_subscription: "password"
pool_id_subscription: "pool-id"

##FOR SATELLITE
url_package_satellite: "http://satellite-server64.asia-east1-b.c.oc-nuup-ac-234223.internal/pub/katello-ca-consumer-latest.noarch.rpm"
org_name_satellite: "initial_organization_prueba"
act_key_satellite: "ocp311-key-activation"
install_agent_satellite: "true"

##Copy rsa option
copy_rsa_by_inventory: "false"

##GENERATE LIST HOST IN Inventory
generate_host_list: false
path_host_ip_list: "host-ip-list"

##List IP MANUAL For copy rsa | ONLY if cfg_copy_rsa_by_inventory is set to false
list_ip: "gluster-reg1.us-central1-c.c.oc-nuup-ac-234223.internal;gluster-reg2.us-central1-c.c.oc-nuup-ac-234223.internal;gluster1.europe-west4-a.c.oc-nuup-ac-234223.internal;gluster2.europe-west4-a.c.oc-nuup-ac-234223.internal;gluster3.europe-west4-a.c.oc-nuup-ac-234223.internal;node1.us-east1-b.c.oc-nuup-ac-234223.internal;node2.us-east1-b.c.oc-nuup-ac-234223.internal;infra1.us-east1-b.c.oc-nuup-ac-234223.internal;infra2.us-east1-b.c.oc-nuup-ac-234223.internal;lb.europe-north1-a.c.oc-nuup-ac-234223.internal;master1.us-east1-b.c.oc-nuup-ac-234223.internal"

##CONFIGURE NODES
configure_nodes: "false"
password_nodes: "r3dh4t1!"

#OPENSHIFT OPTIONS
ocp_is_gluster: "true"
