---
- hosts: masters, nodes, infras, new_nodes
  vars_files:
    - ../config-ocp-tools.yml
  tasks:
    - name: Limpiando suscripciones
      shell: |
        subscription-manager remove --all
        subscription-manager clean
        subscription-manager register --username={{ subscription_user }} --password={{ subscription_password }}
        subscription-manager attach --pool={{ subscription_pool_id }}
      vars: 
        subscription_user: "{{ username_subscription }}"
        subscription_password: "{{ password_subscription }}"
        subscription_pool_id: "{{ pool_id_subscription }}
    - name: Desabilitando repositorios
      shell: |
        subscription-manager repos --disable="*"
    - name: Habilitando repositorios adecuados
      shell: |
        subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.9-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"
    - name: Verificando actualizaciones (yum)
      yum: list=updates update_cache=true
      register: yumoutput
    - name: Actualizando paquetes
      yum:
        name: '*'
        state: latest
    - name: Instalando paquetes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - nfs-utils
        - wget
        - git
        - net-tools
        - bind-utils
        - yum-utils
        - iptables-services
        - bridge-utils
        - bash-completion
        - kexec-tools
        - sos
        - psacct
        - nano
        - atomic-openshift-utils 
        - docker-1.13.1
    - name: Configurando Docker (1-3)
      shell: |
        rpm -V docker-1.13.1
    - name: Configurando Docker (2-3)
      shell:
        cmd: |
          cat > /etc/sysconfig/docker-storage-setup << EOF
          DEVS=/dev/sdb
          VG=docker-vg
          EOF
    - name: Configurando Docker (3-3)
      shell: |
        docker-storage-setup
        systemctl enable docker
        systemctl start docker
        
- hosts: lb
  vars_files:
    - ../config-ocp-tools.yml
  tasks:
    - name: Limpiando suscripciones
      shell: |
        subscription-manager remove --all
        subscription-manager clean
        subscription-manager register --username={{ subscription_user }} --password={{ subscription_password }}
        subscription-manager attach --pool={{ subscription_pool_id }}
      vars: 
        subscription_user: "{{ username_subscription }}"
        subscription_password: "{{ password_subscription }}"
        subscription_pool_id: "{{ pool_id_subscription }}
    - name: Desabilitando repositorios
      shell: |
        subscription-manager repos --disable="*"
    - name: Habilitando repositorios adecuados
      shell: |
        subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.9-rpms" --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"
    - name: Verificando actualizaciones (yum)
      yum: list=updates update_cache=true
      register: yumoutput
    - name: Actualizando paquetes
      yum:
        name: '*'
        state: latest
- hosts: nfs
  vars_files:
    - ../config-ocp-tools.yml
  tasks:
    - name: Limpiando suscripciones
      shell: |
        subscription-manager remove --all
        subscription-manager clean
        subscription-manager register --username={{ subscription_user }} --password={{ subscription_password }}
        subscription-manager attach --pool={{ subscription_pool_id }}
      vars: 
        subscription_user: "{{ username_subscription }}"
        subscription_password: "{{ password_subscription }}"
        subscription_pool_id: "{{ pool_id_subscription }}
    - name: Desabilitando repositorios
      shell: |
        subscription-manager repos --disable="*"
    - name: Habilitando repositorios adecuados
      shell: |
        subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms"
    - name: Verificando actualizaciones (yum)
      yum: list=updates update_cache=true
      register: yumoutput
    - name: Actualizando paquetes
      yum:
        name: '*'
        state: latest
    - name: Instalando paquetes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - nfs-utils
        - rpcbind
    - name: Creando carpetas registry, logging, metrics
      shell: |
        mkdir -p /var/export/registry
        mkdir -p /var/export/logging
        mkdir -p /var/export/metrics
        chown -R nfsnobody:nfsnobody /var/export/
        chmod -R 700 /var/export/
    - name: Configurando NFS (1/3)
      shell: |
        setsebool -P virt_use_nfs=true
        setsebool -P virt_sandbox_use_nfs=true
        firewall-cmd --reload
        chown -R nfsnobody:nfsnobody /var/export/
        chmod -R 700 /var/export/
    - name: Configurando NFS (2/3)
      shell:
        cmd: |
          cat > /etc/exports.d/ocp.exports << EOF
          /var/export/metrics *(rw,async,root_squash)
          /var/export/registry *(rw,async,root_squash)
          /var/export/logging *(rw,async,root_squash)
          EOF
    - name: Configurando NFS (3/3)
      shell:
        cmd: |
          exportfs -a
          systemctl restart nfs-server.service nfs.service
          showmount -e
...