---
- hosts: masters, nodes, infras
  vars_files:
    - ../config-ocp-tools.yml
  tasks:
    - name: Habilitando repositorios adecuados
      shell: |
        rm -rf /etc/sysconfig/docker-storage-setup
        rm -rf /etc/sysconfig/docker-storage
        yum -y remove docker
        rm -rf /var/lib/docker 
        yum -y install docker-1.13.1
        wipefs --all --force /dev/sdb
      register: task_result
    - name: Reboot immediately if there was a change.
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: task_result is changed
    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: task_result is changed
...